### PR TITLE
[First guides] Index descriptions, excerpts and canonical URLs

### PR DESCRIPTION
**Pull request by ChristopheDujarric**

### CODE REVIEW

**Review by scharrier — APPROVED** [review]
LGTM 👍

**Comment by paulRbr** [comment]
Shall we remove both pages `/help/getting-started/api-platform/` and `/help/getting-started/fastapi/` now that we have some proper “guides” pages for that type of content?

**Comment by thimy** [comment]
Good point, but this will be done elsewhere as this PR is for descriptions :)

**Comment by paulRbr** [comment]
> as this PR is for descriptions :)

Sorry I didn't understand your answer @thimy.

Right now, and since the merge of this PR we have duplicate contents in the hub:
- https://docs.bump.sh/guides/bump-sh-tutorials/api-platform/
- https://docs.bump.sh/help/getting-started/api-platform/

I'm not a SEO pro, but I think it's bad to have duplicate content

**Pull request merged**
