### PR TITLE
help: add edit on github button

### PR DESCRIPTION
**Pull request by thimy**
As said in title, this puts a link to github file at the bottom of the page.

### CODE REVIEW

**Comment by ChristopheDujarric** [comment]
* Can we highlight it a little with a thin border? For now it feels like it's "floating"
* Can we also have this button on Guides? As guides have a different style and can be rather long in content, I'd imagine having the button in the left margin, below all of the rest
image

**Review by paulRbr — APPROVED** [review]
:+1: thanks for this improvement

**Comment by thimy** [comment]
Added the button on the guide page with a border to make it stand out more.

image

**Comment by ChristopheDujarric** [comment]
Thanks a lot! Just one small glitch, seen only on ultra-wide monitors:
image

**Pull request merged**
