### PR TITLE
style: make footer closer to bump.sh website footer

### PR DESCRIPTION
**Pull request by thimy**
Changed colors and paddings.

### CODE REVIEW

**Comment by scharrier** [comment]
I'm not convinced by the current alignment, is there an issue here?

Capture d’écran 2023-02-03 à 15 07 36

Shouldn't we have the same left padding than the menu? 

Could we also add the bottom links?

Capture d’écran 2023-02-03 à 15 09 01

Thanks a lot!

**Comment by thimy** [comment]
I broke the `.container` class earlier and restored it to be centered.
It actually _is_ centered 😬 

What's happening here is the default styles have a width defined for columns, and since our links are quite short they leave a big space on their right.

I tried a better alignment but it felt very empty, but it should be better if we had the missing columns from the website footer, may I?

About the bottom links, I can't find a way to edit the template and I'm not happy about it. 🙃

**Comment by thimy** [comment]
Updated the footer styles for a flex-based column centering and updated bottom links style.
The empty space feels a bit awkward to me but we can fill it in another PR if needed.

**Review by paulRbr — APPROVED** [review]
Thanks :blue_heart:

**Review by scharrier — APPROVED** [review]
Ok to keep the current margin, thanks for enhancing it :)
LGTM.

**Pull request merged**
