### PR TITLE
Add product updates

### PR DESCRIPTION
**Pull request by scharrier**
Once this PR is merged, it will add a "Product updates" section to the hub, replacing https://headwayapp.co/bump-changelog.

### CODE REVIEW

**Comment by thimy** [comment]
Hey there, I added a commit to style the product changelog page, let me know if this needs more. :)

**Comment by scharrier** [comment]
@thimy thanks. Can we also fix the titles? (Same size and weight as in the documentation titles, and remove the "blue") 🙏

**Comment by thimy** [comment]
Done!

**Comment by thimy** [comment]
Oops, didn't think about this page, done now!

**Pull request merged**
