### PR TITLE
Add link to Bump.sh in the navbar

### PR DESCRIPTION
**Pull request by ChristopheDujarric**
Add a link to https://bump.sh in the navbar.

### CODE REVIEW

**Review by paulRbr — APPROVED** [review]
Thanks for this PR.

Should we also add a link to the front-office directly (to `https://bump.sh/docs`)? With a link value like **“Your APIs”** (wording to be defined..)

**Comment by ChristopheDujarric** [comment]
@jayk-u what do you think about PaulR's idea?

**Comment by scharrier** [comment]
It doesn't look pretty good: the text isn't correctly vertically aligned, the icon size isn't the same as the dark mode's one, and it feels like it's a bit "alone".

Capture d’écran 2023-02-06 à 14 43 49

Shouldn't we add this link once we have a top bar with other links? We could also add a link to our API reference, and maybe a signin/signup one? But this needs a bit of discussion/design.

I would be in favor of replacing this PR by a more global one adding all the top nav links we want.WDYT?

**Comment by ChristopheDujarric** [comment]
OK with @scharrier 's suggestion

**Pull request closed without merging**
